[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.3", features = [ "rfcomm", "bluetoothd" ] }
bytebuffer = "2.3.0"
evdev = "0.13.1"
futures = "0.3.31"
qwreey-utility-rs = "0.1.2"
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.17"
utf8_iter = "1.0.4"
ws = "0.9.2"
